export const ActionTypes = {
  REQUEST_GET_ARTICLES: 'articles/REQUEST_GET_ARTICLES',
  SUCCESS_GET_ARTICLES: 'articles/SUCCESS_GET_ARTICLES',
  FAILURE_GET_ARTICLES: 'articles/FAILURE_GET_ARTICLES',
}